### ISSUE TITLE
It is not registered to npm repository.

### ISSUE THREAD

**Issue by aboboev** [richburke/react-native-png#2]
I think it is great library. however, why didn't you add as npm repository?
I could use it only by adding src directory to project folder.

**Comment by richburke** [comment]
Hi @alexwmsoft, thanks for your comment and question.  In fact I did have it up on NPM until very recently.  I took it down because, while I don't see any immediate threats of security exploitation, I recognize it as a possible threat--particularly given that I don't have time to maintain this project.

If you have the time and/or desire, feel free to fork it.  Regardless, I hope you find the library to be helpful!
